### ISSUE TITLE
README: assignment-categories

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/assignment-categories#1]
Please get the new README.md from the [Child Template](https://github.com/byuitechops/child-template/blob/master/README.md) and fill it out for your child module. Push it to your child module's repository. 

If you have questions, ask Zach, Daniel, or Josh.

**Comment by zachintosh** [comment]
I think you did this already. Go ahead and close this if you did.

**Comment by sethchilders92** [comment]
Completed
